import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/modules/Home.module.css'

import Upload from "../../public/icons/upload.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <div className="container fixed-bottom">
            <div className="container chat">
              <div className="row d-flex">
                <div className="col-auto">
                  <button className="is-icon__upload btn" title="Upload"></button>
                </div>
                <div className="col">
                  chat
                </div>
                <div className="col-auto">
                  <button className="is-icon__send btn" title="Send"></button>
                </div>
              </div>
            </div>
          </div>
      </main>
    </>
  )
}
